package stdlib

import (
	"bytes"
	_ "embed"
	"encoding/gob"

	"github.com/jdkato/gnols/internal/gno"
)

//go:embed stdlib.gob
var encoded []byte

// Packages is a list of all the packages in the Gno standard library.
//
// We use it to power live, in-editor intelisense such as:
//
// - Hover tooltips
// - Autocomplete
//
// The list is generated by the `/cmd/gen` command.
var Packages = []gno.Package{}

func init() {
	dec := gob.NewDecoder(bytes.NewReader(encoded))
	if err := dec.Decode(&Packages); err != nil {
		panic(err)
	}
}
